name: release

on:
  push: 
    branches:
      - '*'

steps:
  - uses: actions/checkout@v4
  - name: create an issue
    uses: dacbd/create-issue-action@main
    with:
      token: ${{ secrets.TOKEN }}
      title: Simple test issue
      body: my new issue