name: release

on:
  push: 
    branches:
      - '*'

jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create an issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ secrets.TOKEN }}
          title: Simple test issue
          body: my new issue rq2